export const DEMO_PARAMETERS = Object.freeze({
  version: "DEMO-2026-01",
  label: "Valores de demostracion — no aprobados para operacion institucional",
  investigationTermDays: 20,
  victimsTermDays: 30,
  dayType: "CALENDARIO_DEMO",
  tieBreak: "menor carga, ultima asignacion mas antigua, identificador estable",
});

export function createDemoSeed() {
  const now = "2026-09-01T14:00:00.000Z";
  return {
    counters: { investigation: 4, victims: 4 },
    users: [
      demoUser(
        "demo-admin",
        "Administrador del sistema",
        "administrador",
        "Administrador del sistema",
        "AMBAS",
      ),
      demoUser(
        "demo-defensor",
        "Defensor/a solicitante",
        "defensor",
        "Defensor/a solicitante",
        "INVESTIGACION",
      ),
      demoUser(
        "demo-investigador",
        "Investigador/a de campo 01",
        "investigador",
        "Investigador/a",
        "INVESTIGACION",
        "inv-demo-02",
      ),
      demoUser(
        "demo-pag-investigacion",
        "PAG Investigación",
        "pag_investigacion",
        "PAG Investigación",
        "INVESTIGACION",
      ),
      demoUser(
        "demo-rjv",
        "Representante judicial de víctimas",
        "rjv",
        "Representante judicial de víctimas",
        "VICTIMAS",
      ),
      demoUser(
        "demo-pag-victimas",
        "PAG Víctimas",
        "pag_victimas",
        "PAG Víctimas",
        "VICTIMAS",
      ),
      demoUser(
        "demo-perito-psicologia",
        "Perito Psicología 01",
        "perito",
        "Perito Psicología 01",
        "VICTIMAS",
        "per-demo-psi-01",
      ),
      demoUser(
        "demo-perito-financiero",
        "Perito Financiero 01",
        "perito",
        "Perito Financiero 01",
        "VICTIMAS",
        "per-demo-fin-01",
      ),
    ],
    professionals: [
      {
        id: "inv-demo-01",
        area: "INVESTIGACION",
        displayName: "Investigador/a de campo 01",
        specialties: ["INVESTIGACION_CAMPO", "BALISTICA"],
        coverages: ["BOGOTA"],
        laws: [],
        available: true,
        demoBaseLoad: 1,
        lastAssignmentAt: "2026-08-20T10:00:00.000Z",
      },
      {
        id: "inv-demo-02",
        area: "INVESTIGACION",
        displayName: "Profesional de investigación 02",
        specialties: ["INVESTIGACION_CAMPO", "ANALISIS_INFORMACION"],
        coverages: ["BOGOTA", "CUNDINAMARCA"],
        laws: [],
        available: true,
        demoBaseLoad: 0,
        lastAssignmentAt: "2026-08-10T10:00:00.000Z",
      },
      {
        id: "inv-demo-03",
        area: "INVESTIGACION",
        displayName: "Profesional de investigación 03",
        specialties: [
          "INVESTIGACION_CAMPO",
          "BALISTICA",
          "ANALISIS_INFORMACION",
        ],
        coverages: ["BOGOTA"],
        laws: [],
        available: false,
        demoBaseLoad: 0,
        lastAssignmentAt: null,
      },
      {
        id: "per-demo-psi-01",
        area: "VICTIMAS",
        displayName: "Perito Psicología 01",
        specialties: ["PSICOLOGICO"],
        coverages: ["BOGOTA", "CUNDINAMARCA"],
        laws: ["LEY_1448", "LEY_975"],
        available: true,
        demoBaseLoad: 0,
        lastAssignmentAt: "2026-08-12T10:00:00.000Z",
      },
      {
        id: "per-demo-psi-02",
        area: "VICTIMAS",
        displayName: "Perito Psicología 02",
        specialties: ["PSICOLOGICO"],
        coverages: ["BOGOTA"],
        laws: ["LEY_975"],
        available: true,
        demoBaseLoad: 0,
        lastAssignmentAt: "2026-08-05T10:00:00.000Z",
      },
      {
        id: "per-demo-fin-01",
        area: "VICTIMAS",
        displayName: "Perito Financiero 01",
        specialties: ["ADMINISTRATIVO_FINANCIERO"],
        coverages: ["BOGOTA", "CUNDINAMARCA"],
        laws: ["LEY_1448", "LEY_975"],
        available: true,
        demoBaseLoad: 0,
        lastAssignmentAt: "2026-08-15T10:00:00.000Z",
      },
      {
        id: "per-demo-fin-02",
        area: "VICTIMAS",
        displayName: "Perito Financiero 02",
        specialties: ["ADMINISTRATIVO_FINANCIERO"],
        coverages: ["BOGOTA"],
        laws: ["LEY_1448"],
        available: false,
        demoBaseLoad: 0,
        lastAssignmentAt: null,
      },
    ],
    requests: [
      {
        id: "INV-2026-0001",
        area: "INVESTIGACION",
        ownerUserId: "demo-defensor",
        externalId: "110016000049202600001",
        summary: "Misión de investigación de campo",
        createdAt: now,
        items: [
          {
            id: "MT-2026-0001",
            service: "INVESTIGACION_CAMPO",
            region: "BOGOTA",
            law: null,
            status: "EN_EJECUCION",
            assigneeId: "inv-demo-01",
            dueDate: "2026-09-21",
            progress: 40,
            reportReference: null,
            assignment: seedAssignment(
              "inv-demo-01",
              "Investigador/a de campo 01",
              now,
            ),
            timeline: [
              event(
                now,
                null,
                "RADICADA",
                "demo-defensor",
                "Solicitud de misión radicada",
              ),
              event(
                now,
                "RADICADA",
                "ASIGNADA",
                "sistema-demo",
                "Asignación automática ejecutada",
              ),
              event(
                now,
                "ASIGNADA",
                "EN_EJECUCION",
                "demo-investigador",
                "Misión iniciada",
              ),
            ],
          },
        ],
      },
      {
        id: "SVP-2026-0001",
        area: "VICTIMAS",
        ownerUserId: "demo-rjv",
        externalId: "RAD-2026-0001",
        summary: "Solicitud de valoración financiera",
        createdAt: now,
        persons: [{ alias: "Persona vinculada 001", type: "DIRECTA" }],
        items: [
          {
            id: "VIC-ITEM-DEMO-0001",
            service: "ADMINISTRATIVO_FINANCIERO",
            region: "BOGOTA",
            law: "LEY_1448",
            status: "CERRADA",
            assigneeId: "per-demo-fin-01",
            dueDate: "2026-10-01",
            progress: 100,
            reportReference: "F171-2026-0001",
            assignment: seedAssignment(
              "per-demo-fin-01",
              "Perito Financiero 01",
              now,
            ),
            timeline: [
              event(
                now,
                null,
                "PENDIENTE_APROBACION_PAG",
                "demo-rjv",
                "Solicitud pericial enviada",
              ),
              event(
                now,
                "PENDIENTE_APROBACION_PAG",
                "APROBADA_REPARTO",
                "demo-pag-victimas",
                "Aprobación previa registrada",
              ),
              event(
                now,
                "APROBADA_REPARTO",
                "ASIGNADA",
                "sistema-demo",
                "Asignación automática ejecutada",
              ),
              event(
                now,
                "ASIGNADA",
                "EN_EJECUCION",
                "demo-perito-financiero",
                "Peritaje iniciado",
              ),
              event(
                now,
                "EN_EJECUCION",
                "CERRADA",
                "demo-perito-financiero",
                "F-171 registrado; servicio cerrado",
              ),
            ],
          },
        ],
      },
      {
        id: "INV-2026-0002",
        area: "INVESTIGACION",
        ownerUserId: "demo-defensor",
        externalId: "110016000049202600002",
        summary: "Misión de análisis de información",
        createdAt: "2026-08-28T15:00:00.000Z",
        items: [
          {
            id: "MT-2026-0002",
            service: "ANALISIS_INFORMACION",
            region: "BOGOTA",
            law: null,
            status: "INFORME_ENTREGADO",
            assigneeId: "inv-demo-02",
            dueDate: "2026-09-17",
            progress: 100,
            reportReference: "INF-2026-0002",
            assignment: seedAssignment(
              "inv-demo-02",
              "Profesional de investigación 02",
              "2026-08-28T15:10:00.000Z",
            ),
            timeline: [
              event(
                "2026-08-28T15:00:00.000Z",
                null,
                "RADICADA",
                "demo-defensor",
                "Solicitud radicada y validada",
              ),
              event(
                "2026-08-28T15:10:00.000Z",
                "RADICADA",
                "ASIGNADA",
                "sistema-demo",
                "Asignación automática ejecutada",
              ),
              event(
                "2026-08-29T13:00:00.000Z",
                "ASIGNADA",
                "EN_EJECUCION",
                "demo-investigador",
                "Misión iniciada",
              ),
              event(
                "2026-09-01T16:00:00.000Z",
                "EN_EJECUCION",
                "INFORME_ENTREGADO",
                "demo-investigador",
                "Informe entregado para revisión PAG",
              ),
            ],
          },
        ],
      },
      {
        id: "INV-2026-0003",
        area: "INVESTIGACION",
        ownerUserId: "demo-defensor",
        externalId: "110016000049202600003",
        summary: "Misión de balística forense cerrada",
        createdAt: "2026-08-12T14:00:00.000Z",
        items: [
          {
            id: "MT-2026-0003",
            service: "BALISTICA",
            region: "BOGOTA",
            law: null,
            status: "CERRADA",
            assigneeId: "inv-demo-01",
            dueDate: "2026-09-01",
            progress: 100,
            reportReference: "INF-2026-0003",
            assignment: seedAssignment(
              "inv-demo-01",
              "Investigador/a de campo 01",
              "2026-08-12T14:05:00.000Z",
            ),
            timeline: [
              event(
                "2026-08-12T14:00:00.000Z",
                null,
                "RADICADA",
                "demo-defensor",
                "Solicitud de misión radicada",
              ),
              event(
                "2026-08-12T14:05:00.000Z",
                "RADICADA",
                "ASIGNADA",
                "sistema-demo",
                "Asignación automática ejecutada",
              ),
              event(
                "2026-08-13T13:00:00.000Z",
                "ASIGNADA",
                "EN_EJECUCION",
                "demo-investigador",
                "Misión iniciada",
              ),
              event(
                "2026-08-25T15:00:00.000Z",
                "EN_EJECUCION",
                "INFORME_ENTREGADO",
                "demo-investigador",
                "Informe entregado",
              ),
              event(
                "2026-08-26T14:00:00.000Z",
                "INFORME_ENTREGADO",
                "CERRADA",
                "demo-pag-investigacion",
                "Entrega aprobada por PAG Investigación",
              ),
            ],
          },
        ],
      },
      {
        id: "SVP-2026-0002",
        area: "VICTIMAS",
        ownerUserId: "demo-rjv",
        externalId: "RAD-2026-0002",
        summary: "Solicitud pericial pendiente de aprobación previa",
        createdAt: "2026-09-01T15:00:00.000Z",
        persons: [
          { alias: "Persona vinculada 002", type: "DIRECTA" },
          { alias: "Persona vinculada 003", type: "INDIRECTA" },
        ],
        items: [
          {
            id: "VIC-ITEM-DEMO-0002",
            service: "PSICOLOGICO",
            region: "BOGOTA",
            law: "LEY_975",
            status: "PENDIENTE_APROBACION_PAG",
            assigneeId: null,
            dueDate: null,
            progress: 0,
            reportReference: null,
            assignment: null,
            timeline: [
              event(
                "2026-09-01T15:00:00.000Z",
                null,
                "PENDIENTE_APROBACION_PAG",
                "demo-rjv",
                "Solicitud enviada a aprobación previa",
              ),
            ],
          },
        ],
      },
      {
        id: "SVP-2026-0003",
        area: "VICTIMAS",
        ownerUserId: "demo-rjv",
        externalId: "RAD-2026-0003",
        summary: "Solicitud de valoración psicológica asignada",
        createdAt: "2026-08-30T14:00:00.000Z",
        persons: [{ alias: "Persona vinculada 004", type: "DIRECTA" }],
        items: [
          {
            id: "VIC-ITEM-DEMO-0003",
            service: "PSICOLOGICO",
            region: "BOGOTA",
            law: "LEY_1448",
            status: "ASIGNADA",
            assigneeId: "per-demo-psi-01",
            dueDate: "2026-09-29",
            progress: 0,
            reportReference: null,
            assignment: seedAssignment(
              "per-demo-psi-01",
              "Perito Psicología 01",
              "2026-08-30T14:10:00.000Z",
            ),
            timeline: [
              event(
                "2026-08-30T14:00:00.000Z",
                null,
                "PENDIENTE_APROBACION_PAG",
                "demo-rjv",
                "Solicitud pericial enviada",
              ),
              event(
                "2026-08-30T14:05:00.000Z",
                "PENDIENTE_APROBACION_PAG",
                "APROBADA_REPARTO",
                "demo-pag-victimas",
                "Aprobación previa registrada",
              ),
              event(
                "2026-08-30T14:10:00.000Z",
                "APROBADA_REPARTO",
                "ASIGNADA",
                "sistema-demo",
                "Asignación automática ejecutada",
              ),
            ],
          },
        ],
      },
    ],
  };
}

function demoUser(id, fullName, role, roleLabel, area, executorId = null) {
  return {
    id,
    document: id,
    password: null,
    fullName,
    accounts: [
      {
        id: `account-${id}`,
        email: `${id}@demo.invalid`,
        role,
        roleLabel,
        area,
        initials: fullName
          .split(" ")
          .slice(0, 2)
          .map((part) => part[0])
          .join(""),
        executorId,
      },
    ],
  };
}

function seedAssignment(selectedId, selectedName, createdAt) {
  return {
    policyVersion: DEMO_PARAMETERS.version,
    demoParametersLabel: DEMO_PARAMETERS.label,
    selectedId,
    selectedName,
    selectedReason:
      "Asignación automática según especialidad, cobertura, disponibilidad y carga",
    evaluated: [],
    createdAt,
  };
}

function event(at, from, to, actor, message) {
  return { at, from, to, actor, message };
}
