CREATE TABLE SIGIP_SCHEMA_VERSION (
  VERSION_ID VARCHAR2(20 CHAR) NOT NULL,
  DESCRIPTION VARCHAR2(300 CHAR) NOT NULL,
  CHECKSUM VARCHAR2(64 CHAR) NOT NULL,
  APPLIED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  APPLIED_BY VARCHAR2(128 CHAR) NOT NULL,
  CONSTRAINT PK_SIGIP_SCHEMA_VERSION PRIMARY KEY (VERSION_ID)
);
