CREATE TABLE SIGIP_AREA (
  AREA_ID VARCHAR2(36 CHAR) NOT NULL, CODIGO VARCHAR2(50 CHAR) NOT NULL,
  NOMBRE VARCHAR2(200 CHAR) NOT NULL, ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
  VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_AREA PRIMARY KEY (AREA_ID), CONSTRAINT UK_SIGIP_AREA_COD_VIG UNIQUE (CODIGO, VIGENTE_DESDE),
  CONSTRAINT CK_SIGIP_AREA_ACT CHECK (ACTIVO IN ('S','N')), CONSTRAINT CK_SIGIP_AREA_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE TABLE SIGIP_REGIONAL (
  REGIONAL_ID VARCHAR2(36 CHAR) NOT NULL, CODIGO VARCHAR2(80 CHAR) NOT NULL,
  NOMBRE VARCHAR2(200 CHAR) NOT NULL, ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
  VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_REGIONAL PRIMARY KEY (REGIONAL_ID), CONSTRAINT UK_SIGIP_REG_COD_VIG UNIQUE (CODIGO, VIGENTE_DESDE),
  CONSTRAINT CK_SIGIP_REG_ACT CHECK (ACTIVO IN ('S','N')), CONSTRAINT CK_SIGIP_REG_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE TABLE SIGIP_GEOGRAFIA (
  GEOGRAFIA_ID VARCHAR2(36 CHAR) NOT NULL, GEOGRAFIA_PADRE_ID VARCHAR2(36 CHAR),
  CODIGO VARCHAR2(80 CHAR) NOT NULL, NOMBRE VARCHAR2(200 CHAR) NOT NULL, TIPO_GEOGRAFIA VARCHAR2(40 CHAR) NOT NULL,
  ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL, VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_GEOGRAFIA PRIMARY KEY (GEOGRAFIA_ID), CONSTRAINT FK_SIGIP_GEO_PADRE FOREIGN KEY (GEOGRAFIA_PADRE_ID) REFERENCES SIGIP_GEOGRAFIA (GEOGRAFIA_ID),
  CONSTRAINT UK_SIGIP_GEO_COD_VIG UNIQUE (TIPO_GEOGRAFIA, CODIGO, VIGENTE_DESDE), CONSTRAINT CK_SIGIP_GEO_ACT CHECK (ACTIVO IN ('S','N')),
  CONSTRAINT CK_SIGIP_GEO_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE TABLE SIGIP_REGIONAL_GEOGRAFIA (
  REGIONAL_GEOGRAFIA_ID VARCHAR2(36 CHAR) NOT NULL, REGIONAL_ID VARCHAR2(36 CHAR) NOT NULL, GEOGRAFIA_ID VARCHAR2(36 CHAR) NOT NULL,
  ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL, VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_REG_GEO PRIMARY KEY (REGIONAL_GEOGRAFIA_ID), CONSTRAINT FK_SIGIP_RG_REG FOREIGN KEY (REGIONAL_ID) REFERENCES SIGIP_REGIONAL (REGIONAL_ID),
  CONSTRAINT FK_SIGIP_RG_GEO FOREIGN KEY (GEOGRAFIA_ID) REFERENCES SIGIP_GEOGRAFIA (GEOGRAFIA_ID),
  CONSTRAINT UK_SIGIP_RG_VIG UNIQUE (REGIONAL_ID, GEOGRAFIA_ID, VIGENTE_DESDE), CONSTRAINT CK_SIGIP_RG_ACT CHECK (ACTIVO IN ('S','N')),
  CONSTRAINT CK_SIGIP_RG_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE TABLE SIGIP_ROL (
  ROL_ID VARCHAR2(36 CHAR) NOT NULL, CODIGO VARCHAR2(80 CHAR) NOT NULL, NOMBRE VARCHAR2(200 CHAR) NOT NULL,
  ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL, VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_ROL PRIMARY KEY (ROL_ID), CONSTRAINT UK_SIGIP_ROL_COD_VIG UNIQUE (CODIGO, VIGENTE_DESDE),
  CONSTRAINT CK_SIGIP_ROL_ACT CHECK (ACTIVO IN ('S','N')), CONSTRAINT CK_SIGIP_ROL_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE TABLE SIGIP_USUARIO (
  USUARIO_ID VARCHAR2(36 CHAR) NOT NULL, SUJETO_IDENTIDAD VARCHAR2(255 CHAR) NOT NULL,
  NOMBRE_MOSTRAR VARCHAR2(200 CHAR) NOT NULL, ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
  CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_USUARIO PRIMARY KEY (USUARIO_ID), CONSTRAINT UK_SIGIP_USUARIO_SUJ UNIQUE (SUJETO_IDENTIDAD),
  CONSTRAINT CK_SIGIP_USUARIO_ACT CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE SIGIP_USUARIO_ROL (
  USUARIO_ROL_ID VARCHAR2(36 CHAR) NOT NULL, USUARIO_ID VARCHAR2(36 CHAR) NOT NULL,
  ROL_ID VARCHAR2(36 CHAR) NOT NULL, AREA_ID VARCHAR2(36 CHAR) NOT NULL, REGIONAL_ID VARCHAR2(36 CHAR),
  TIPO_ALCANCE VARCHAR2(40 CHAR) NOT NULL, ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
  VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_USR_ROL PRIMARY KEY (USUARIO_ROL_ID), CONSTRAINT FK_SIGIP_UR_USR FOREIGN KEY (USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID),
  CONSTRAINT FK_SIGIP_UR_ROL FOREIGN KEY (ROL_ID) REFERENCES SIGIP_ROL (ROL_ID), CONSTRAINT FK_SIGIP_UR_AREA FOREIGN KEY (AREA_ID) REFERENCES SIGIP_AREA (AREA_ID),
  CONSTRAINT FK_SIGIP_UR_REG FOREIGN KEY (REGIONAL_ID) REFERENCES SIGIP_REGIONAL (REGIONAL_ID),
  CONSTRAINT UK_SIGIP_UR_VIG UNIQUE (USUARIO_ID, ROL_ID, AREA_ID, REGIONAL_ID, VIGENTE_DESDE), CONSTRAINT CK_SIGIP_UR_ACT CHECK (ACTIVO IN ('S','N')),
  CONSTRAINT CK_SIGIP_UR_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE TABLE SIGIP_ESPECIALIDAD_SERVICIO (
  ESPECIALIDAD_SERVICIO_ID VARCHAR2(36 CHAR) NOT NULL, AREA_ID VARCHAR2(36 CHAR) NOT NULL,
  CODIGO VARCHAR2(100 CHAR) NOT NULL, NOMBRE VARCHAR2(200 CHAR) NOT NULL, TIPO_SERVICIO VARCHAR2(40 CHAR) NOT NULL,
  ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL, VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_ESP_SERV PRIMARY KEY (ESPECIALIDAD_SERVICIO_ID), CONSTRAINT FK_SIGIP_ES_AREA FOREIGN KEY (AREA_ID) REFERENCES SIGIP_AREA (AREA_ID),
  CONSTRAINT UK_SIGIP_ES_COD_VIG UNIQUE (AREA_ID, CODIGO, VIGENTE_DESDE), CONSTRAINT CK_SIGIP_ES_ACT CHECK (ACTIVO IN ('S','N')),
  CONSTRAINT CK_SIGIP_ES_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE TABLE SIGIP_COBERTURA_TERRITORIAL (
  COBERTURA_TERRITORIAL_ID VARCHAR2(36 CHAR) NOT NULL, AREA_ID VARCHAR2(36 CHAR) NOT NULL,
  ESPECIALIDAD_SERVICIO_ID VARCHAR2(36 CHAR) NOT NULL, USUARIO_ID VARCHAR2(36 CHAR) NOT NULL,
  REGIONAL_ID VARCHAR2(36 CHAR), GEOGRAFIA_ID VARCHAR2(36 CHAR), INCLUIDA CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
  PRIORIDAD NUMBER(9), ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
  VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_COB_TERR PRIMARY KEY (COBERTURA_TERRITORIAL_ID), CONSTRAINT FK_SIGIP_CT_AREA FOREIGN KEY (AREA_ID) REFERENCES SIGIP_AREA (AREA_ID),
  CONSTRAINT FK_SIGIP_CT_ESP FOREIGN KEY (ESPECIALIDAD_SERVICIO_ID) REFERENCES SIGIP_ESPECIALIDAD_SERVICIO (ESPECIALIDAD_SERVICIO_ID),
  CONSTRAINT FK_SIGIP_CT_USR FOREIGN KEY (USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID), CONSTRAINT FK_SIGIP_CT_REG FOREIGN KEY (REGIONAL_ID) REFERENCES SIGIP_REGIONAL (REGIONAL_ID),
  CONSTRAINT FK_SIGIP_CT_GEO FOREIGN KEY (GEOGRAFIA_ID) REFERENCES SIGIP_GEOGRAFIA (GEOGRAFIA_ID),
  CONSTRAINT CK_SIGIP_CT_DEST CHECK (REGIONAL_ID IS NOT NULL OR GEOGRAFIA_ID IS NOT NULL), CONSTRAINT CK_SIGIP_CT_INC CHECK (INCLUIDA IN ('S','N')),
  CONSTRAINT CK_SIGIP_CT_ACT CHECK (ACTIVO IN ('S','N')), CONSTRAINT CK_SIGIP_CT_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE INDEX IX_SIGIP_USR_ROL_ACT ON SIGIP_USUARIO_ROL (USUARIO_ID, ACTIVO);
CREATE INDEX IX_SIGIP_COB_TERR_BUSQ ON SIGIP_COBERTURA_TERRITORIAL (AREA_ID, ESPECIALIDAD_SERVICIO_ID, ACTIVO);
