CREATE TABLE SIGIP_CASO (
  CASO_ID VARCHAR2(36 CHAR) NOT NULL, AREA_ID VARCHAR2(36 CHAR) NOT NULL, IDENTIFICADOR_EXTERNO VARCHAR2(120 CHAR) NOT NULL,
  ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL, CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_CASO PRIMARY KEY (CASO_ID), CONSTRAINT FK_SIGIP_CASO_AREA FOREIGN KEY (AREA_ID) REFERENCES SIGIP_AREA (AREA_ID),
  CONSTRAINT UK_SIGIP_CASO_EXT UNIQUE (AREA_ID, IDENTIFICADOR_EXTERNO), CONSTRAINT CK_SIGIP_CASO_ACT CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE SIGIP_SOLICITUD (
  SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL, CASO_ID VARCHAR2(36 CHAR) NOT NULL, AREA_ID VARCHAR2(36 CHAR) NOT NULL,
  SOLICITANTE_USUARIO_ID VARCHAR2(36 CHAR) NOT NULL, ANIO NUMBER(4), CONSECUTIVO NUMBER(18), ESTADO VARCHAR2(80 CHAR) NOT NULL,
  VERSION NUMBER(18) DEFAULT 1 NOT NULL, CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  ANULADO_EN TIMESTAMP(6) WITH TIME ZONE, MOTIVO_ANULACION VARCHAR2(1000 CHAR),
  CONSTRAINT PK_SIGIP_SOLICITUD PRIMARY KEY (SOLICITUD_ID), CONSTRAINT FK_SIGIP_SOL_CASO FOREIGN KEY (CASO_ID) REFERENCES SIGIP_CASO (CASO_ID),
  CONSTRAINT FK_SIGIP_SOL_AREA FOREIGN KEY (AREA_ID) REFERENCES SIGIP_AREA (AREA_ID), CONSTRAINT FK_SIGIP_SOL_USR FOREIGN KEY (SOLICITANTE_USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID),
  CONSTRAINT UK_SIGIP_SOL_CONS UNIQUE (AREA_ID, ANIO, CONSECUTIVO), CONSTRAINT CK_SIGIP_SOL_VER CHECK (VERSION > 0),
  CONSTRAINT CK_SIGIP_SOL_ANUL CHECK ((ANULADO_EN IS NULL AND MOTIVO_ANULACION IS NULL) OR (ANULADO_EN IS NOT NULL AND MOTIVO_ANULACION IS NOT NULL))
);

CREATE TABLE SIGIP_ITEM_SOLICITUD (
  ITEM_SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL, SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL,
  ESPECIALIDAD_SERVICIO_ID VARCHAR2(36 CHAR) NOT NULL, REGIONAL_ID VARCHAR2(36 CHAR), ITEM_PADRE_ID VARCHAR2(36 CHAR),
  CONSECUTIVO_HIJO NUMBER(18) NOT NULL, ESTADO VARCHAR2(80 CHAR) NOT NULL, FECHA_LIMITE TIMESTAMP(6) WITH TIME ZONE,
  VERSION NUMBER(18) DEFAULT 1 NOT NULL, CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_ITEM_SOL PRIMARY KEY (ITEM_SOLICITUD_ID), CONSTRAINT FK_SIGIP_ITEM_SOL FOREIGN KEY (SOLICITUD_ID) REFERENCES SIGIP_SOLICITUD (SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_ITEM_ESP FOREIGN KEY (ESPECIALIDAD_SERVICIO_ID) REFERENCES SIGIP_ESPECIALIDAD_SERVICIO (ESPECIALIDAD_SERVICIO_ID),
  CONSTRAINT FK_SIGIP_ITEM_REG FOREIGN KEY (REGIONAL_ID) REFERENCES SIGIP_REGIONAL (REGIONAL_ID), CONSTRAINT FK_SIGIP_ITEM_PADRE FOREIGN KEY (ITEM_PADRE_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID),
  CONSTRAINT UK_SIGIP_ITEM_CONS UNIQUE (SOLICITUD_ID, CONSECUTIVO_HIJO), CONSTRAINT CK_SIGIP_ITEM_VER CHECK (VERSION > 0)
);

CREATE TABLE SIGIP_PERSONA_SOLICITUD (
  PERSONA_SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL, SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL,
  REFERENCIA_PERSONA VARCHAR2(255 CHAR) NOT NULL, TIPO_RELACION VARCHAR2(80 CHAR) NOT NULL,
  ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL, CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_PER_SOL PRIMARY KEY (PERSONA_SOLICITUD_ID), CONSTRAINT FK_SIGIP_PER_SOL FOREIGN KEY (SOLICITUD_ID) REFERENCES SIGIP_SOLICITUD (SOLICITUD_ID),
  CONSTRAINT UK_SIGIP_PER_REF UNIQUE (SOLICITUD_ID, REFERENCIA_PERSONA, TIPO_RELACION), CONSTRAINT CK_SIGIP_PER_ACT CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE SIGIP_RELACION_PERSONA (
  RELACION_PERSONA_ID VARCHAR2(36 CHAR) NOT NULL, SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL,
  PERSONA_ORIGEN_ID VARCHAR2(36 CHAR) NOT NULL, PERSONA_DESTINO_ID VARCHAR2(36 CHAR) NOT NULL, CODIGO_RELACION VARCHAR2(80 CHAR) NOT NULL,
  ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL, VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_REL_PER PRIMARY KEY (RELACION_PERSONA_ID), CONSTRAINT FK_SIGIP_RP_SOL FOREIGN KEY (SOLICITUD_ID) REFERENCES SIGIP_SOLICITUD (SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_RP_ORIG FOREIGN KEY (PERSONA_ORIGEN_ID) REFERENCES SIGIP_PERSONA_SOLICITUD (PERSONA_SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_RP_DEST FOREIGN KEY (PERSONA_DESTINO_ID) REFERENCES SIGIP_PERSONA_SOLICITUD (PERSONA_SOLICITUD_ID),
  CONSTRAINT CK_SIGIP_RP_DIST CHECK (PERSONA_ORIGEN_ID <> PERSONA_DESTINO_ID), CONSTRAINT CK_SIGIP_RP_ACT CHECK (ACTIVO IN ('S','N')),
  CONSTRAINT CK_SIGIP_RP_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE INDEX IX_SIGIP_SOL_CASO ON SIGIP_SOLICITUD (CASO_ID, CREADO_EN);
CREATE INDEX IX_SIGIP_ITEM_EST ON SIGIP_ITEM_SOLICITUD (ESTADO, ESPECIALIDAD_SERVICIO_ID);
CREATE INDEX IX_SIGIP_PER_SOL ON SIGIP_PERSONA_SOLICITUD (SOLICITUD_ID, ACTIVO);
