CREATE TABLE SIGIP_DECISION_ASIGNACION (
  DECISION_ASIGNACION_ID VARCHAR2(36 CHAR) NOT NULL, ITEM_SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL,
  VERSION_POLITICA VARCHAR2(100 CHAR) NOT NULL, CODIGO_RESULTADO VARCHAR2(80 CHAR) NOT NULL,
  USUARIO_SELECCIONADO_ID VARCHAR2(36 CHAR), REGLA_DESEMPATE VARCHAR2(200 CHAR), EXPLICACION_JSON CLOB NOT NULL,
  CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_DEC_ASG PRIMARY KEY (DECISION_ASIGNACION_ID), CONSTRAINT FK_SIGIP_DA_ITEM FOREIGN KEY (ITEM_SOLICITUD_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_DA_SEL FOREIGN KEY (USUARIO_SELECCIONADO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID), CONSTRAINT CK_SIGIP_DA_JSON CHECK (EXPLICACION_JSON IS JSON)
);

CREATE TABLE SIGIP_CANDIDATO_DECISION (
  CANDIDATO_DECISION_ID VARCHAR2(36 CHAR) NOT NULL, DECISION_ASIGNACION_ID VARCHAR2(36 CHAR) NOT NULL,
  USUARIO_ID VARCHAR2(36 CHAR) NOT NULL, ELEGIBLE CHAR(1 CHAR) NOT NULL, POSICION NUMBER(18), METRICAS_JSON CLOB NOT NULL,
  CONSTRAINT PK_SIGIP_CAND_DEC PRIMARY KEY (CANDIDATO_DECISION_ID), CONSTRAINT FK_SIGIP_CD_DEC FOREIGN KEY (DECISION_ASIGNACION_ID) REFERENCES SIGIP_DECISION_ASIGNACION (DECISION_ASIGNACION_ID),
  CONSTRAINT FK_SIGIP_CD_USR FOREIGN KEY (USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID), CONSTRAINT UK_SIGIP_CD_USR UNIQUE (DECISION_ASIGNACION_ID, USUARIO_ID),
  CONSTRAINT CK_SIGIP_CD_ELEG CHECK (ELEGIBLE IN ('S','N')), CONSTRAINT CK_SIGIP_CD_JSON CHECK (METRICAS_JSON IS JSON)
);

CREATE TABLE SIGIP_EXCLUSION_CANDIDATO (
  EXCLUSION_CANDIDATO_ID VARCHAR2(36 CHAR) NOT NULL, CANDIDATO_DECISION_ID VARCHAR2(36 CHAR) NOT NULL,
  CODIGO_REGLA VARCHAR2(120 CHAR) NOT NULL, EXPLICACION VARCHAR2(1000 CHAR) NOT NULL,
  CONSTRAINT PK_SIGIP_EXC_CAND PRIMARY KEY (EXCLUSION_CANDIDATO_ID), CONSTRAINT FK_SIGIP_EC_CAND FOREIGN KEY (CANDIDATO_DECISION_ID) REFERENCES SIGIP_CANDIDATO_DECISION (CANDIDATO_DECISION_ID),
  CONSTRAINT UK_SIGIP_EC_REGLA UNIQUE (CANDIDATO_DECISION_ID, CODIGO_REGLA)
);

CREATE TABLE SIGIP_ASIGNACION (
  ASIGNACION_ID VARCHAR2(36 CHAR) NOT NULL, ITEM_SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL,
  DECISION_ASIGNACION_ID VARCHAR2(36 CHAR), RESPONSABLE_USUARIO_ID VARCHAR2(36 CHAR) NOT NULL,
  TIPO_ASIGNACION VARCHAR2(40 CHAR) NOT NULL, VERSION_POLITICA VARCHAR2(100 CHAR) NOT NULL,
  ES_VIGENTE CHAR(1 CHAR) DEFAULT 'S' NOT NULL, VERSION NUMBER(18) DEFAULT 1 NOT NULL,
  ASIGNADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL, FINALIZADO_EN TIMESTAMP(6) WITH TIME ZONE,
  MOTIVO VARCHAR2(1000 CHAR) NOT NULL, AUTORIZADO_POR VARCHAR2(36 CHAR),
  CONSTRAINT PK_SIGIP_ASIGNACION PRIMARY KEY (ASIGNACION_ID), CONSTRAINT FK_SIGIP_ASG_ITEM FOREIGN KEY (ITEM_SOLICITUD_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_ASG_DEC FOREIGN KEY (DECISION_ASIGNACION_ID) REFERENCES SIGIP_DECISION_ASIGNACION (DECISION_ASIGNACION_ID),
  CONSTRAINT FK_SIGIP_ASG_RESP FOREIGN KEY (RESPONSABLE_USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID), CONSTRAINT FK_SIGIP_ASG_AUT FOREIGN KEY (AUTORIZADO_POR) REFERENCES SIGIP_USUARIO (USUARIO_ID),
  CONSTRAINT CK_SIGIP_ASG_VIG CHECK (ES_VIGENTE IN ('S','N')), CONSTRAINT CK_SIGIP_ASG_VER CHECK (VERSION > 0),
  CONSTRAINT CK_SIGIP_ASG_FIN CHECK ((ES_VIGENTE = 'S' AND FINALIZADO_EN IS NULL) OR ES_VIGENTE = 'N')
);

CREATE UNIQUE INDEX UX_SIGIP_ASG_VIGENTE ON SIGIP_ASIGNACION (CASE WHEN ES_VIGENTE = 'S' THEN ITEM_SOLICITUD_ID END);

CREATE TABLE SIGIP_HISTORIAL_ASIGNACION (
  HISTORIAL_ASIGNACION_ID VARCHAR2(36 CHAR) NOT NULL, ASIGNACION_ID VARCHAR2(36 CHAR) NOT NULL, ITEM_SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL,
  ACCION VARCHAR2(80 CHAR) NOT NULL, RESPONSABLE_USUARIO_ID VARCHAR2(36 CHAR) NOT NULL, RESPONSABLE_ANTERIOR_ID VARCHAR2(36 CHAR),
  ACTOR_USUARIO_ID VARCHAR2(36 CHAR), ACTOR_REFERENCIA VARCHAR2(128 CHAR) NOT NULL, MOTIVO VARCHAR2(1000 CHAR) NOT NULL,
  SOPORTE_REFERENCIA VARCHAR2(500 CHAR), OCURRIDO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_HIST_ASG PRIMARY KEY (HISTORIAL_ASIGNACION_ID), CONSTRAINT FK_SIGIP_HASG_ASG FOREIGN KEY (ASIGNACION_ID) REFERENCES SIGIP_ASIGNACION (ASIGNACION_ID),
  CONSTRAINT FK_SIGIP_HASG_ITEM FOREIGN KEY (ITEM_SOLICITUD_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_HASG_RESP FOREIGN KEY (RESPONSABLE_USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID), CONSTRAINT FK_SIGIP_HASG_ANT FOREIGN KEY (RESPONSABLE_ANTERIOR_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID),
  CONSTRAINT FK_SIGIP_HASG_ACT FOREIGN KEY (ACTOR_USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID)
);

CREATE TABLE SIGIP_TRANSICION_ESTADO (
  TRANSICION_ESTADO_ID VARCHAR2(36 CHAR) NOT NULL, ITEM_SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL, AREA_ID VARCHAR2(36 CHAR) NOT NULL,
  ESTADO_ANTERIOR VARCHAR2(80 CHAR), ESTADO_NUEVO VARCHAR2(80 CHAR) NOT NULL, ACTOR_USUARIO_ID VARCHAR2(36 CHAR),
  ACTOR_REFERENCIA VARCHAR2(128 CHAR) NOT NULL, ACTOR_ROL_CODIGO VARCHAR2(80 CHAR) NOT NULL, MOTIVO VARCHAR2(1000 CHAR) NOT NULL,
  DOCUMENTO_SOPORTE_ID VARCHAR2(36 CHAR), OCURRIDO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_TRANS_EST PRIMARY KEY (TRANSICION_ESTADO_ID), CONSTRAINT FK_SIGIP_TR_ITEM FOREIGN KEY (ITEM_SOLICITUD_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_TR_AREA FOREIGN KEY (AREA_ID) REFERENCES SIGIP_AREA (AREA_ID), CONSTRAINT FK_SIGIP_TR_ACT FOREIGN KEY (ACTOR_USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID)
);

CREATE TABLE SIGIP_NOVEDAD (
  NOVEDAD_ID VARCHAR2(36 CHAR) NOT NULL, USUARIO_ID VARCHAR2(36 CHAR) NOT NULL, TIPO_NOVEDAD_CODIGO VARCHAR2(80 CHAR) NOT NULL,
  AUTORIZADO_POR VARCHAR2(36 CHAR) NOT NULL, BLOQUEA_NUEVAS_ASIGNACIONES CHAR(1 CHAR) NOT NULL, MOTIVO VARCHAR2(1000 CHAR) NOT NULL,
  VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_NOVEDAD PRIMARY KEY (NOVEDAD_ID), CONSTRAINT FK_SIGIP_NOV_USR FOREIGN KEY (USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID),
  CONSTRAINT FK_SIGIP_NOV_AUT FOREIGN KEY (AUTORIZADO_POR) REFERENCES SIGIP_USUARIO (USUARIO_ID), CONSTRAINT CK_SIGIP_NOV_BLOQ CHECK (BLOQUEA_NUEVAS_ASIGNACIONES IN ('S','N')),
  CONSTRAINT CK_SIGIP_NOV_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE INDEX IX_SIGIP_HASG_ITEM ON SIGIP_HISTORIAL_ASIGNACION (ITEM_SOLICITUD_ID, OCURRIDO_EN);
CREATE INDEX IX_SIGIP_TR_ITEM ON SIGIP_TRANSICION_ESTADO (ITEM_SOLICITUD_ID, OCURRIDO_EN);

CREATE OR REPLACE TRIGGER TR_SIGIP_HASG_APPEND BEFORE UPDATE OR DELETE ON SIGIP_HISTORIAL_ASIGNACION BEGIN RAISE_APPLICATION_ERROR(-20001, 'Historial de asignacion append-only'); END;
/
CREATE OR REPLACE TRIGGER TR_SIGIP_TRANS_APPEND BEFORE UPDATE OR DELETE ON SIGIP_TRANSICION_ESTADO BEGIN RAISE_APPLICATION_ERROR(-20002, 'Transiciones append-only'); END;
/
CREATE OR REPLACE TRIGGER TR_SIGIP_DEC_ASG_APPEND BEFORE UPDATE OR DELETE ON SIGIP_DECISION_ASIGNACION BEGIN RAISE_APPLICATION_ERROR(-20005, 'Decisiones de asignacion append-only'); END;
/
CREATE OR REPLACE TRIGGER TR_SIGIP_CAND_DEC_APPEND BEFORE UPDATE OR DELETE ON SIGIP_CANDIDATO_DECISION BEGIN RAISE_APPLICATION_ERROR(-20006, 'Candidatos de decision append-only'); END;
/
CREATE OR REPLACE TRIGGER TR_SIGIP_EXC_CAND_APPEND BEFORE UPDATE OR DELETE ON SIGIP_EXCLUSION_CANDIDATO BEGIN RAISE_APPLICATION_ERROR(-20007, 'Exclusiones de candidato append-only'); END;
/
