CREATE TABLE SIGIP_DOCUMENTO (
  DOCUMENTO_ID VARCHAR2(36 CHAR) NOT NULL, CASO_ID VARCHAR2(36 CHAR) NOT NULL, SOLICITUD_ID VARCHAR2(36 CHAR), ITEM_SOLICITUD_ID VARCHAR2(36 CHAR),
  TIPO_DOCUMENTO VARCHAR2(100 CHAR) NOT NULL, VERSION_VIGENTE NUMBER(18) DEFAULT 0 NOT NULL, ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
  CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_DOCUMENTO PRIMARY KEY (DOCUMENTO_ID), CONSTRAINT FK_SIGIP_DOC_CASO FOREIGN KEY (CASO_ID) REFERENCES SIGIP_CASO (CASO_ID),
  CONSTRAINT FK_SIGIP_DOC_SOL FOREIGN KEY (SOLICITUD_ID) REFERENCES SIGIP_SOLICITUD (SOLICITUD_ID), CONSTRAINT FK_SIGIP_DOC_ITEM FOREIGN KEY (ITEM_SOLICITUD_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID),
  CONSTRAINT CK_SIGIP_DOC_ACT CHECK (ACTIVO IN ('S','N')), CONSTRAINT CK_SIGIP_DOC_VER CHECK (VERSION_VIGENTE >= 0)
);

CREATE TABLE SIGIP_VERSION_DOCUMENTO (
  VERSION_DOCUMENTO_ID VARCHAR2(36 CHAR) NOT NULL, DOCUMENTO_ID VARCHAR2(36 CHAR) NOT NULL, NUMERO_VERSION NUMBER(18) NOT NULL,
  REFERENCIA_ALMACEN VARCHAR2(1000 CHAR) NOT NULL, HASH_SHA256 CHAR(64 CHAR) NOT NULL, AUTOR_USUARIO_ID VARCHAR2(36 CHAR) NOT NULL,
  MOTIVO VARCHAR2(1000 CHAR) NOT NULL, ESTADO VARCHAR2(80 CHAR) NOT NULL, CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_VER_DOC PRIMARY KEY (VERSION_DOCUMENTO_ID), CONSTRAINT FK_SIGIP_VER_DOC FOREIGN KEY (DOCUMENTO_ID) REFERENCES SIGIP_DOCUMENTO (DOCUMENTO_ID),
  CONSTRAINT FK_SIGIP_VER_AUT FOREIGN KEY (AUTOR_USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID), CONSTRAINT UK_SIGIP_VER_NUM UNIQUE (DOCUMENTO_ID, NUMERO_VERSION),
  CONSTRAINT CK_SIGIP_VER_POS CHECK (NUMERO_VERSION > 0)
);

ALTER TABLE SIGIP_TRANSICION_ESTADO ADD CONSTRAINT FK_SIGIP_TR_DOC FOREIGN KEY (DOCUMENTO_SOPORTE_ID) REFERENCES SIGIP_DOCUMENTO (DOCUMENTO_ID);

CREATE TABLE SIGIP_PRODUCTO (
  PRODUCTO_ID VARCHAR2(36 CHAR) NOT NULL, ITEM_SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL, DOCUMENTO_ID VARCHAR2(36 CHAR) NOT NULL,
  TIPO_PRODUCTO VARCHAR2(80 CHAR) NOT NULL, ESTADO VARCHAR2(80 CHAR) NOT NULL, CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_PRODUCTO PRIMARY KEY (PRODUCTO_ID), CONSTRAINT FK_SIGIP_PROD_ITEM FOREIGN KEY (ITEM_SOLICITUD_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_PROD_DOC FOREIGN KEY (DOCUMENTO_ID) REFERENCES SIGIP_DOCUMENTO (DOCUMENTO_ID)
);

CREATE TABLE SIGIP_AMPLIACION (
  AMPLIACION_ID VARCHAR2(36 CHAR) NOT NULL, ITEM_ORIGINAL_ID VARCHAR2(36 CHAR) NOT NULL, ITEM_RESULTANTE_ID VARCHAR2(36 CHAR) NOT NULL,
  AUTORIZADO_POR VARCHAR2(36 CHAR), MOTIVO VARCHAR2(1000 CHAR) NOT NULL, CREADO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_AMPLIACION PRIMARY KEY (AMPLIACION_ID), CONSTRAINT FK_SIGIP_AMP_ORIG FOREIGN KEY (ITEM_ORIGINAL_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_AMP_RES FOREIGN KEY (ITEM_RESULTANTE_ID) REFERENCES SIGIP_ITEM_SOLICITUD (ITEM_SOLICITUD_ID), CONSTRAINT FK_SIGIP_AMP_AUT FOREIGN KEY (AUTORIZADO_POR) REFERENCES SIGIP_USUARIO (USUARIO_ID),
  CONSTRAINT UK_SIGIP_AMP_RES UNIQUE (ITEM_RESULTANTE_ID)
);

CREATE TABLE SIGIP_TRANSFERENCIA_DEFENSOR (
  TRANSFERENCIA_DEFENSOR_ID VARCHAR2(36 CHAR) NOT NULL, SOLICITUD_ID VARCHAR2(36 CHAR) NOT NULL,
  USUARIO_ANTERIOR_ID VARCHAR2(36 CHAR) NOT NULL, USUARIO_NUEVO_ID VARCHAR2(36 CHAR) NOT NULL, AUTORIZADO_POR VARCHAR2(36 CHAR),
  MOTIVO VARCHAR2(1000 CHAR) NOT NULL, OCURRIDO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_SIGIP_TRANS_DEF PRIMARY KEY (TRANSFERENCIA_DEFENSOR_ID), CONSTRAINT FK_SIGIP_TD_SOL FOREIGN KEY (SOLICITUD_ID) REFERENCES SIGIP_SOLICITUD (SOLICITUD_ID),
  CONSTRAINT FK_SIGIP_TS_ANT FOREIGN KEY (USUARIO_ANTERIOR_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID), CONSTRAINT FK_SIGIP_TS_NUEVO FOREIGN KEY (USUARIO_NUEVO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID),
  CONSTRAINT FK_SIGIP_TS_AUT FOREIGN KEY (AUTORIZADO_POR) REFERENCES SIGIP_USUARIO (USUARIO_ID)
);

CREATE INDEX IX_SIGIP_DOC_CASO ON SIGIP_DOCUMENTO (CASO_ID, TIPO_DOCUMENTO);
CREATE OR REPLACE TRIGGER TR_SIGIP_VER_DOC_APPEND BEFORE UPDATE OR DELETE ON SIGIP_VERSION_DOCUMENTO BEGIN RAISE_APPLICATION_ERROR(-20003, 'Versiones documentales append-only'); END;
/
