CREATE TABLE SIGIP_PARAMETRO (
  PARAMETRO_ID VARCHAR2(36 CHAR) NOT NULL, CLAVE VARCHAR2(120 CHAR) NOT NULL, AREA_ID VARCHAR2(36 CHAR), ESPECIALIDAD_SERVICIO_ID VARCHAR2(36 CHAR),
  TIPO_VALOR VARCHAR2(40 CHAR) NOT NULL, VALOR VARCHAR2(2000 CHAR) NOT NULL, ESTADO_APROBACION VARCHAR2(60 CHAR) NOT NULL,
  REFERENCIA_EVIDENCIA VARCHAR2(500 CHAR), ACTIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
  VIGENTE_DESDE TIMESTAMP(6) WITH TIME ZONE NOT NULL, VIGENTE_HASTA TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_SIGIP_PARAMETRO PRIMARY KEY (PARAMETRO_ID), CONSTRAINT FK_SIGIP_PAR_AREA FOREIGN KEY (AREA_ID) REFERENCES SIGIP_AREA (AREA_ID),
  CONSTRAINT FK_SIGIP_PAR_ESP FOREIGN KEY (ESPECIALIDAD_SERVICIO_ID) REFERENCES SIGIP_ESPECIALIDAD_SERVICIO (ESPECIALIDAD_SERVICIO_ID),
  CONSTRAINT CK_SIGIP_PAR_ACT CHECK (ACTIVO IN ('S','N')), CONSTRAINT CK_SIGIP_PAR_VIG CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA > VIGENTE_DESDE)
);

CREATE TABLE SIGIP_AUDITORIA (
  AUDITORIA_ID VARCHAR2(36 CHAR) NOT NULL, TIPO_ENTIDAD VARCHAR2(100 CHAR) NOT NULL, ENTIDAD_ID VARCHAR2(36 CHAR) NOT NULL,
  OPERACION VARCHAR2(100 CHAR) NOT NULL, ACTOR_USUARIO_ID VARCHAR2(36 CHAR), ACTOR_REFERENCIA VARCHAR2(128 CHAR) NOT NULL,
  ACTOR_ROL_CODIGO VARCHAR2(80 CHAR) NOT NULL, ESTADO_ANTERIOR VARCHAR2(80 CHAR), ESTADO_NUEVO VARCHAR2(80 CHAR),
  MOTIVO VARCHAR2(1000 CHAR) NOT NULL, OCURRIDO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL, CORRELACION_ID VARCHAR2(128 CHAR), METADATOS_JSON CLOB NOT NULL,
  CONSTRAINT PK_SIGIP_AUDITORIA PRIMARY KEY (AUDITORIA_ID), CONSTRAINT FK_SIGIP_AUD_ACT FOREIGN KEY (ACTOR_USUARIO_ID) REFERENCES SIGIP_USUARIO (USUARIO_ID),
  CONSTRAINT CK_SIGIP_AUD_JSON CHECK (METADATOS_JSON IS JSON)
);

CREATE TABLE SIGIP_OUTBOX (
  OUTBOX_ID VARCHAR2(36 CHAR) NOT NULL, TIPO_AGREGADO VARCHAR2(100 CHAR) NOT NULL, AGREGADO_ID VARCHAR2(36 CHAR) NOT NULL,
  TIPO_EVENTO VARCHAR2(150 CHAR) NOT NULL, CLAVE_IDEMPOTENCIA VARCHAR2(150 CHAR) NOT NULL, PAYLOAD_JSON CLOB NOT NULL,
  ESTADO VARCHAR2(40 CHAR) DEFAULT 'PENDIENTE' NOT NULL, OCURRIDO_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  DISPONIBLE_EN TIMESTAMP(6) WITH TIME ZONE NOT NULL, ENVIADO_EN TIMESTAMP(6) WITH TIME ZONE,
  INTENTOS NUMBER(18) DEFAULT 0 NOT NULL, ULTIMO_ERROR VARCHAR2(1000 CHAR),
  CONSTRAINT PK_SIGIP_OUTBOX PRIMARY KEY (OUTBOX_ID), CONSTRAINT UK_SIGIP_OUTBOX_IDEM UNIQUE (CLAVE_IDEMPOTENCIA),
  CONSTRAINT CK_SIGIP_OUT_JSON CHECK (PAYLOAD_JSON IS JSON), CONSTRAINT CK_SIGIP_OUT_INT CHECK (INTENTOS >= 0)
);

CREATE INDEX IX_SIGIP_PAR_BUSQ ON SIGIP_PARAMETRO (CLAVE, AREA_ID, ESPECIALIDAD_SERVICIO_ID, ACTIVO, VIGENTE_DESDE);
CREATE INDEX IX_SIGIP_AUD_ENT ON SIGIP_AUDITORIA (TIPO_ENTIDAD, ENTIDAD_ID, OCURRIDO_EN);
CREATE INDEX IX_SIGIP_OUT_PEND ON SIGIP_OUTBOX (ESTADO, DISPONIBLE_EN);

CREATE OR REPLACE TRIGGER TR_SIGIP_AUD_APPEND BEFORE UPDATE OR DELETE ON SIGIP_AUDITORIA BEGIN RAISE_APPLICATION_ERROR(-20004, 'Auditoria append-only'); END;
/
